name: Build Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install requirements
        run: |
          pip install -r cl_requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --add-data ".\whisper-assets:whisper\assets" client.py

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: /O+

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          overwrite: true
          body: |
            This is a automated release completed by GitHub Actions.
          draft: false
          prerelease: false
      - name: Upload EXE
        id: upload-client
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/client.exe
          asset_name: client.exe
          asset_content_type: application/octet-stream

      - name: Upload Installer
        id: upload-installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: output/FreeScribeInstaller.exe
          asset_name: FreeScribeInstaller_windows.exe
          asset_content_type: application/octet-stream
