name: Build Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install requirements
        run: |
          pip install -r client_requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --add-data ".\src\FreeScribe.client\whisper-assets:whisper\assets" --name freescribe-client .\src\FreeScribe.client\client.py

      - name: Set up NSIS
        uses: joncloud/makensis-action@1c9f4bf2ea0c771147db31a2f3a7f5d8705c0105 # v4.1 commit hash

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is a automated release completed by GitHub Actions.
          draft: false
          prerelease: false
      - name: Upload EXE
        id: upload-client
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/freescribe-client.exe
          asset_name: freescribe-client.exe
          asset_content_type: application/octet-stream

      - name: Upload Installer
        id: upload-installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/FreeScribeInstaller.exe
          asset_name: FreeScribeInstaller_windows.exe
          asset_content_type: application/octet-stream
